"""Segunda version

Revision ID: 88e8b01c23fb
Revises: dd7ac0010ec4
Create Date: 2025-04-10 11:44:06.883714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e8b01c23fb'
down_revision: Union[str, None] = 'dd7ac0010ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sintoma',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sintoma_id'), 'sintoma', ['id'], unique=False)
    op.create_index(op.f('ix_sintoma_nombre'), 'sintoma', ['nombre'], unique=False)
    op.create_table('sintomas_consulta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sintoma_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sintoma_id'], ['sintoma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sintomas_consulta_id'), 'sintomas_consulta', ['id'], unique=False)
    op.drop_column('resultado', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultado', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sintomas_consulta_id'), table_name='sintomas_consulta')
    op.drop_table('sintomas_consulta')
    op.drop_index(op.f('ix_sintoma_nombre'), table_name='sintoma')
    op.drop_index(op.f('ix_sintoma_id'), table_name='sintoma')
    op.drop_table('sintoma')
    # ### end Alembic commands ###
