"""Tercer version

Revision ID: 9898f34693f1
Revises: 88e8b01c23fb
Create Date: 2025-04-10 11:50:18.713315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9898f34693f1'
down_revision: Union[str, None] = '88e8b01c23fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sintomas_enfermedad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sintoma_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sintoma_id'], ['sintoma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sintomas_enfermedad_id'), 'sintomas_enfermedad', ['id'], unique=False)
    op.add_column('sintomas_consulta', sa.Column('resultado_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sintomas_consulta', 'resultado', ['resultado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sintomas_consulta', type_='foreignkey')
    op.drop_column('sintomas_consulta', 'resultado_id')
    op.drop_index(op.f('ix_sintomas_enfermedad_id'), table_name='sintomas_enfermedad')
    op.drop_table('sintomas_enfermedad')
    # ### end Alembic commands ###
