"""Cuarta version

Revision ID: b79418543b1b
Revises: 9898f34693f1
Create Date: 2025-04-10 11:56:11.803102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79418543b1b'
down_revision: Union[str, None] = '9898f34693f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfermedad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enfermedad_descripcion'), 'enfermedad', ['descripcion'], unique=False)
    op.create_index(op.f('ix_enfermedad_id'), 'enfermedad', ['id'], unique=False)
    op.create_index(op.f('ix_enfermedad_nombre'), 'enfermedad', ['nombre'], unique=False)
    op.add_column('sintomas_enfermedad', sa.Column('enfermedad_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sintomas_enfermedad', 'enfermedad', ['enfermedad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sintomas_enfermedad', type_='foreignkey')
    op.drop_column('sintomas_enfermedad', 'enfermedad_id')
    op.drop_index(op.f('ix_enfermedad_nombre'), table_name='enfermedad')
    op.drop_index(op.f('ix_enfermedad_id'), table_name='enfermedad')
    op.drop_index(op.f('ix_enfermedad_descripcion'), table_name='enfermedad')
    op.drop_table('enfermedad')
    # ### end Alembic commands ###
