"""Primera version

Revision ID: dd7ac0010ec4
Revises: 
Create Date: 2025-04-10 11:25:57.241315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7ac0010ec4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_nombre'), 'usuario', ['nombre'], unique=False)
    op.create_table('consulta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('razon', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consulta_id'), 'consulta', ['id'], unique=False)
    op.create_index(op.f('ix_consulta_razon'), 'consulta', ['razon'], unique=False)
    op.create_table('resultado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('diagnostico_final', sa.String(), nullable=False),
    sa.Column('consulta_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consulta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultado_diagnostico_final'), 'resultado', ['diagnostico_final'], unique=False)
    op.create_index(op.f('ix_resultado_id'), 'resultado', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultado_id'), table_name='resultado')
    op.drop_index(op.f('ix_resultado_diagnostico_final'), table_name='resultado')
    op.drop_table('resultado')
    op.drop_index(op.f('ix_consulta_razon'), table_name='consulta')
    op.drop_index(op.f('ix_consulta_id'), table_name='consulta')
    op.drop_table('consulta')
    op.drop_index(op.f('ix_usuario_nombre'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
